[features]
seeds = false
[programs.localnet]
test_question_pda = "6uWRze9WV6LHM4jQUGCxxb2jjmrUcYqq6wWPWVdEaogg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/relly/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
